### PR TITLE
Update JenkinsfileRT and PyTests

### PR DESCRIPTION
**Pull request by mdlpstsci**
Based on advice from Joe H. with regard to the Astroquery/Artifactory issues for RT Testing...
Test 1: Properly address the location of the output directory.  The jenkins_shared_ci_utils should resolve to "/srv/jenkins/workspace/NAME/JOBNUM/clone/tests_output".

### CODE REVIEW

**Comment by jhunkeler** [comment]
The upload succeeded. Nice! You can probably fix the 3.10 and 3.11 dev builds by explicitly setting `-std=gnu99` in `CFLAGS`:

Old
```
bc3.env_vars = ['TEST_BIGDATA=https://bytesalad.stsci.edu/artifactory']
```

New
```
bc3.env_vars = [
    'TEST_BIGDATA=https://bytesalad.stsci.edu/artifactory',
    'CFLAGS=-std=gnu99'
]
```

**Comment by mdlpstsci** [comment]
@jhunkeler The CFLAGS update did not seem to cure the issue - alas.  On a different issue, I am puzzled as the drizzlepac-results area (at least under acs, but maybe all the directories) only has output for the XFAIL tests.  What I really want are the results for the FAIL tests.  Where is the setting which controls this output?

**Comment by jhunkeler** [comment]
Always something :tm:. I wasn't expecting https://github.com/spacetelescope/jenkins_shared_ci_utils/blob/9c339a16062eab6d1adeb1ded7da5b20ab21ff76/vars/utils.groovy#L805 to interpret the second `=` in `'CFLAGS=-std=gnu99'`.

The strings from `BuildConfig.env_vars` are modified then stored in `BuildConfig.runtime`:
https://github.com/spacetelescope/jenkins_shared_ci_utils/blob/master/src/BuildConfig.groovy#L34-L36

Since you've uncovered an edge case may want manipulate to the runtime list directly:

```groovy
bc3.runtime.add('CFLAGS=-std=gnu99')
```

Another option is to try passing the environment variable through the build command's shell wherever it is needed...

```groovy
def BUILD_FLAGS = "CFLAGS='-std=gnu99'"
bc3.build_cmds = ["${BUILD_FLAGS} pip install numpy astropy codecov pytest-cov ci-watson==0.5",
		 "${BUILD_FLAGS} pip install -r requirements-dev.txt --upgrade -e '.[test]'",
                 "pip freeze"]
```

>  Where is the setting which controls this output?

https://github.com/spacetelescope/drizzlepac/blob/47809ce3dd9f234649e25d0335cd5f4047c3425b/pyproject.toml#L155

This setting used to live in `setup.cfg` and @dulude had to hack around it when everything started failing in JWST. I don't think he needs to weigh in on this unless nothing was uploaded to `drizzlepac-results`.

**Comment by mdlpstsci** [comment]
@jhunkeler Modifying the runtime list directly did the trick.  

I know the fix for the one failing test, but I am still trying to determine why its updated "truth" is not deposited on Artifactory when other files are successfully put there!

**Comment by mdlpstsci** [comment]
I should also note there were different package versions running under the MacOS:
Python Version [Clang 14.0.6 ]
3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:42:20)
numpy Version -> 1.25.1
astropy Version -> 5.3.1
stwcs Version -> 1.7.2
photutils Version -> 1.8.0

versus Linux:
Python Version [GCC 11.3.0]
3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03)
numpy Version -> 1.24.3 
astropy Version -> 5.2.2 
stwcs Version -> 1.7.2 
photutils Version -> 1.7.0

**Comment by mdlpstsci** [comment]
This PR has been superseded by other PRs.

**Pull request closed without merging**
