### PR TITLE
Rename static mask

### PR DESCRIPTION
**Pull request by stsci-hack**
These changes implement a new naming convention for the common static mask file that gets used by `astrodrizzle.AstroDrizzle()`.  The new name is based on the original input provided to astrodrizzle, and if it is ASN file, the filename defined in the ASN file as the 'output' product.  This results in a dataset unique name for the static mask based on the original input file which will not be confused with the static mask for any other dataset being processed in the same directory.

### CODE REVIEW

**Review by mdlpstsci — APPROVED** [review]
Changes are straightforward and look to be complete.

**Comment by mcara** [comment]
This, in general, looks good. One thing though: in my experience static mask files are usually left over on the disk (i.e., not "cleaned"). Am I wrong? If not, wouldn't this PR result in a large(r) number of files being left over on disk?

**Comment by stsci-hack** [comment]
These static mask files are removed if the 'clean' parameter is set to 'yes'.  They do get left behind when processing does not complete as well.  However, these changes should at least associate these intermediate (temp) files with the dataset being processed so that they only get get cleaned up for the data which has been successfully processed.  I will try to see whether more can be done to clean these files up by identifying when they do get left behind, but that should be handled in a separate PR.

**Review by mcara — APPROVED** [review]
LGTM

**Pull request merged**
