### PR TITLE
pin Python in RTD environment

### PR DESCRIPTION
**Pull request by zacharyburnett**
This PR pins Python to `3.11` in the RTD build environment, to attempt to resolve build errors with the docs

**Checklist for maintainers**
- [ ] added entry in `CHANGELOG.rst` within the relevant release section
- [ ] updated or added relevant tests
- [ ] updated relevant documentation
- [ ] added relevant milestone
- [ ] added relevant label(s)
- [ ] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)

### CODE REVIEW

**Comment by zacharyburnett** [comment]
> @zacharyburnett Is this ready for review?

Yes it should be, there is just a single warning that I'm unsure about:
```
/Users/zburnett/projects/drizzlepac/drizzlepac/haputils/poller_utils.py:docstring of drizzlepac.haputils.poller_utils.interpret_obset_input:38: WARNING: Literal block expected; none found.
```

**Comment by s-goldman** [comment]
> > @zacharyburnett Is this ready for review?
> 
> Yes it should be, there is just a single warning that I'm unsure about:
> 
> ```
> /Users/zburnett/projects/drizzlepac/drizzlepac/haputils/poller_utils.py:docstring of drizzlepac.haputils.poller_utils.interpret_obset_input:38: WARNING: Literal block expected; none found.
> ```

That doesn't seem related. I'll try to fix that in another PR.

**Comment by s-goldman** [comment]
I think we just need to indent the numbered lines. Changing the docstring to the following should work:

`"""

    Parameters
    -----------
    results : str or list
        Input poller file name or Python list of dataset names to be processed as a single visit.
        Dataset names have to be either the filename of a singleton (non-associated exposure) or the
        name of an ASN file (e.g., jabc01010_asn.fits).

    log_level : int
        The desired level of verboseness in the log statements displayed on the screen and written to the
        .log file.

    Returns
    -------
    obset_dict : dict
        Dictionary of obset objects

    tdp_list : list
        list of total detection products

    Notes
    -------
    Interpret the database query for a given obset to prepare the returned
    values for use in generating the names of all the expected output products.

    Input will have formated rows of one of the following three options::

        1) Full poller file
            ib4606c5q_flc.fits,11665,B46,06,1.0,F555W,UVIS,/foo/bar/ib4606c5q_flc.fits
        
        2) Simpler poller file (list); other info taken from file header keywords
            ib4606c5q_flc.fits
        
        3) For updating the WFPC2 SVM aperture keyword using the poller file; it
            is important that there are no spaces within the poller aperture keyword(s)
            ib4606c5q_flc.fits, PC1-FIX;F160BN15

    Full poller files contain filename, proposal_id, program_id, obset_id, exptime, filters, detector, pathname.

    The output dict will have format (as needed by further code for creating the product filenames) of::

        obs_info_dict["single exposure product 00": {"info": '11665 06 wfc3 uvis empty_aperture ib4606c5q f555w drc',
                                                     "files": ['ib4606c5q_flc.fits']}
        .
        .
        .
        obs_info_dict["single exposure product 08": {"info": '11665 06 wfc3 ir empty_aperture ib4606clq f110w drz',
                                                     "files": ['ib4606clq_flt.fits']}

        obs_info_dict["filter product 00": {"info": '11665 06 wfc3 uvis empty_aperture ib4606c5q f555w drc',
                                            "files": ['ib4606c5q_flc.fits', 'ib4606c6q_flc.fits']},
        .
        .
        .
        obs_info_dict["filter product 01": {"info": '11665 06 wfc3 ir empty_aperture ib4606cmq f160w drz',
                                            "files": ['ib4606cmq_flt.fits', 'ib4606crq_flt.fits']},


        obs_info_dict["total detection product 00": {"info": '11665 06 wfc3 uvis empty_aperture ib4606c5q f555w drc',
                                                     "files": ['ib4606c5q_flc.fits', 'ib4606c6q_flc.fits']}
        .
        .
        .
        obs_info_dict["total detection product 01": {"info": '11665 06 wfc3 ir empty_aperture ib4606cmq f160w drz',
                                                     "files": ['ib4606cmq_flt.fits', 'ib4606crq_flt.fits']}

    The aperture keyword, which has a default value of 'empty_aperture' is filled in the case of WFPC2 observations,
    and the use of the two-column format.

    """`

**Comment by zacharyburnett** [comment]
I put the code examples in their own blocks, see https://drizzlepac--1687.org.readthedocs.build/en/1687/reference/runsinglehap.html#drizzlepac.haputils.poller_utils.interpret_obset_input

**Comment by s-goldman** [comment]
That sounds good

**Review by s-goldman — APPROVED** [review]

**Pull request merged**
