### PR TITLE
Set the gain to a value of 1.0 when processing ACS/SBC data

### PR DESCRIPTION
**Pull request by mdlpstsci**
Ensure the photometry routine has a value of 1.0 for the ACS/SBC gain to avoid values being set to nan and causing
all of the sources to be trimmed from the output catalogs.

### CODE REVIEW

**Comment by stsci-hack** [comment]
Would it be simpler to add the if...else statement to the computation of `self.gain` in the init of the base class (Line 501?) for use in both places as once?  
May I also request that you also set this gain value to 1.0 for 'IR' as well as 'SBC'?  That would resolve problems with the photometry errors and swarm detection for WFC3/IR as well.

**Comment by mdlpstsci** [comment]
Indeed, it would.  I guess I misinterpreted (or overinterpreted) our discussion in Slack as I thought you wanted it this way.  In any case, easily addressed.  Will also set the gain for for IR as well.

**Comment by mdlpstsci** [comment]
Review addressed in commit 9666240.

**Review by stsci-hack — APPROVED** [review]
This looks quite efficient.  LGTM.

**Pull request merged**
