### PR TITLE
Fix rtd failure install numpy

### PR DESCRIPTION
**Pull request by mcara**

### CODE REVIEW

**Comment by drdavella** [comment]
@mcara that should be the current behavior: the bot says everything looks good. Or am I missing something?

**Comment by mcara** [comment]
@drdavella See https://github.com/spacetelescope/drizzlepac/pull/182#issuecomment-426095872

**Comment by mcara** [comment]
@drdavella `no-changelog-entry-needed` was added _before_ PR was created.

**Comment by drdavella** [comment]
It should work whether `no-changelog-entry-needed` is set when the PR is created, or afterwards. In any event, I'm confused, because the bot is already demonstrating the behavior you requested. If you remove the label, the bot should update the message to complain, and then if you restore it, the bot should restore the current message.

**Comment by mcara** [comment]
Well the label is here and so is the message. Shouldn't it go away?

**Comment by drdavella** [comment]
No, the message appears in all cases. But in this case it says:

> Everything looks good from my point of view! 👍

**Comment by mcara** [comment]
Oh, I missed _"Everything looks good from my point of view!"_

**Pull request merged**
