### PR TITLE
HLA-1209 Bug fix that allows for user inputs in astrodrizzle with mdriztab=True

### LINKED ISSUE #1739: Inconsistency in command-line interface related to mdriztab=True
_Issue [HLA-1209](https://jira.stsci.edu/browse/HLA-1209) was created on JIRA by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman):_

Testing of the use of AstroDrizzle() for single_visit mosaic generation uncovered a use-case where setting 'mdriztab=True' caused other parameters set on the command line to be ignored; specifically, final_rot. This needs to be sorted out, since any user-specified parameter MUST take precedent at all times.

### PR DESCRIPTION
**Pull request by s-goldman**
Resolves [HLA-1209](https://jira.stsci.edu/browse/HLA-1209)

Closes #1739 

This PR addresses a bug where user inputs are ignored for the astrodrizzle interface when the mdriztab option is enabled. `mdriztab=True` uses the best parameters for the configobj, that were determined by the instument teams, as defaults. This PR aims to insure that the user inputs should overwrite any of these mdriztab defaults. 

In this PR, I was able to pass the user inputs (**input_dir) from `astrodrizzle.astrodrizzle()` to the subsequent calls to `processInput.setCommonInput() `so that, after we merge (`using cfgpars.mergeConfigObj`) the configobj defaults with the mdriztab defaults, we can then merge the resulting configobj with the user inputs (`_overwrite_dict_`). 

In essence this changes makes it so that the code takes default parameters, overwrite them with mdriztab parameters, **and now** overwrites the resulting dictionary with the user parameters. 

A suite of tests should be added to insure that all possible options are correctly being executed. I've created [HLA-1242](https://jira.stsci.edu/browse/HLA-1242) to track the development of these tests. 

**Checklist for maintainers**
- [x] added entry in `CHANGELOG.rst` within the relevant release section
- [ ] updated or added relevant tests
- [x] updated relevant documentation
- [x] added relevant milestone
- [x] added relevant label(s)
- [x] ran regression tests, post a link to the Jenkins job below.
      [How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)

[Jenkins Test](https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FDrizzlepac-Developers-Pull-Requests/detail/Drizzlepac-Developers-Pull-Requests/68/pipeline)

### CODE REVIEW

**Comment by s-goldman** [comment]
One thing that appears missing from the documentation is a description of `wcsmap`. If anyone can find a description, I would like to add it. I can infer from context, but it would be good to have descriptions that are consistent.

**Comment by mdlpstsci** [comment]
Do you mean the WCSMap class in the wcsfunctions.py module?

**Comment by s-goldman** [comment]
> Do you mean the WCSMap class in the wcsfunctions.py module?

Ahh, that may be it, thanks. I'll make sure and then add a note in the documentation.

**Review by mdlpstsci — APPROVED** [review]
After reading the discussion in the issue, I understand what one is trying to achieve.

**Pull request merged**
