### PR TITLE
TST: Turn Sphinx warning into error

### PR DESCRIPTION
**Pull request by pllim**
I'm baaaack!

http://www.sphinx-doc.org/en/master/setuptools.html

### CODE REVIEW

**Comment by pllim** [comment]
@jhunkeler , I don't get it. There is 1 warning but test passed anyway. It is like Jenkins is ignoring setting in `setup.cfg`.

```
build succeeded, 1 warnings.
```

**Comment by mcara** [comment]
@pllim @stsci-hack @jhunkeler If you make changes that are worth communicating to the users, please *DO NOT FORGET TO UPDATE* the [CHANGELOG](https://github.com/spacetelescope/drizzlepac/blob/master/CHANGELOG.rst)

By the way, is it possible to block PRs unless there is an entry added to the changelog???

**Comment by pllim** [comment]
Usually, changes to doc and test do not need change log.

> is it possible to block PRs unless there is an entry added to the changelog?

Yes, Astropy uses a bot to check changelog. If unsatisfactory, bot will request changes. And you can probably set your repo to disable commit until bot approves. @drdavella cloned that bot into `stsci-bot` a while ago but I have not seen it in action.

**Comment by mcara** [comment]
OK, then let's not get overboard, but just do not forget about [CHANGELOG](https://github.com/spacetelescope/drizzlepac/blob/master/CHANGELOG.rst)

**Comment by drdavella** [comment]
I'm late to this discussion, but currently that bot only runs on https://github.com/spacetelescope/asdf. If you want it to be enabled for other repositories, I can help with that.

**Comment by pllim** [comment]
It is Mihai and Warren's call...

**Comment by mcara** [comment]
I discussed the issue with @drdavella offline and it seems that we can ignore the bot when necessary (of it misbehaves) and this addresses all my concerns. Considering the benefit of being reminded to add a changelog entry, I am all for having this bot.

**Comment by pllim** [comment]
Make it so, @drdavella ! :)

**Comment by drdavella** [comment]
This is actually something that needs to be done by someone with admin rights on the repo, but I can provide guidance (once I remind myself how I did it in the first place).

**Comment by pllim** [comment]
Someone removed my power on this repo. Can't help there. Sorry, Dan!

**Comment by mcara** [comment]
> Someone removed my power on this repo.

However, I am sure @jhunkeler would be happy to help.

**Pull request merged**
