### PR TITLE
new check to catch wcs from unnamed primary hdu with extver=1

### PR DESCRIPTION
**Pull request by srodney**
Addresses issue #590

### CODE REVIEW

**Comment by stsci-hack** [comment]
A more fundamental solution has been implemented in #954, where astrodrizzle correctly populates the headers with EXTNAME and EXTVER in all cases.  This admittedly does not help with data already processed, except to allow the users to reprocess their drizzled products to clean up the headers and finally make them FITS-compliant.  This PR should now either be closed without merging to rely on #954 or rebased onto the latest version of the code so that it can finally be merged in.

**Comment by mcara** [comment]
Alternative fix that would create a WCS object with the correct `extname` property (`==` a value that would allow `hdulist[extname]` to work as expected) is in https://github.com/spacetelescope/stwcs/pull/179. That PR fixes the underlying issue.

**Comment by mcara** [comment]
Alternative fix that would create a WCS object with the correct `extname` property (`==` a value that would allow `hdulist[extname]` to work as expected) is in https://github.com/spacetelescope/stwcs/pull/179. That PR fixes the underlying issue.

CC: @stsci-hack

**Comment by mcara** [comment]
fixed via https://github.com/spacetelescope/stwcs/pull/179

**Pull request closed without merging**
