### PR TITLE
Add current dir last to sys.path so that RDT works

### PR DESCRIPTION
**Pull request by mcara**
This fixes `python setup.py build_sphinx` and likely `RTD` but it may affect `python setup.py develop`.

### CODE REVIEW

**Comment by jhunkeler** [comment]
Is there a way to pass `python setup.py build_ext --inplace` on RTD? I don't think the path order matters so much as the shared library not existing relative to the local `./drizzlepac` package sphinx is examining/importing from.

```
$ cd drizzlepac
$ python setup.py install
$ python -c 'import drizzlepac'

# Boom

 Coordinate transformation and image resampling library NOT found!

 Please check the installation of this package to insure C code was built successfully.
Traceback (most recent call last):
  File "/Users/jhunk/Downloads/drizzlepac/drizzlepac/ablot.py", line 27, in <module>
    from . import cdriz
ImportError: cannot import name 'cdriz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jhunk/Downloads/drizzlepac/drizzlepac/__init__.py", line 24, in <module>
    from . import ablot
  File "/Users/jhunk/Downloads/drizzlepac/drizzlepac/ablot.py", line 32, in <module>
    raise ImportError
ImportError
```

Same directory, same everything, but building in-place so the C extensions are injected into the local package:
```
$ python setup.py build_ext --inplace
$ python -c 'import drizzlepac'
# no error
```

**Comment by mcara** [comment]
@jhunkeler I would suggest you try this PR.

**Comment by sosey** [comment]
http://docs.readthedocs.io/en/latest/builds.html suggests they really only use `setup.py intall`

**Comment by sosey** [comment]
why can't the user just use develop or install and then go in docs and `make html` ?

**Comment by sosey** [comment]
@jhunkeler ya lost me a little, if they haven't checked out the repo how will they build the docs locally?

**Comment by mcara** [comment]
I think https://github.com/spacetelescope/drizzlepac/pull/142 may be a more promising approach with fewer potential side-effects so I am withdrawing this PR.

**Pull request closed without merging**
