### PR TITLE
MVM: create documentation page for custom mosaic creation code

### PR DESCRIPTION
**Pull request by dulude**
**Relevant JIRA Ticket**
- [HLA-631](https://jira.stsci.edu/browse/HLA-631)

**Summary of Changes**
- Made a couple of tweaks to make_custom_mosaic.py code (fixed misspellings, minor streamlining/refactoring)
- Spruced up make_custom_mosaic.py docstrings
- Created makecustommosaic.rst file so that a readthedocs html page is created 
- Updated index.rst so that a link to the make_custom_mosaic readthedocs page is added to the main left-hand navigation menu.
- Created blank documentation pages multivisit.rst and runmultihap.rst as placeholders for future development. These pages are not yet linked to anywhere from anywhere in the documentation yet.
- Spruced up which_skycell.py make_poller_files.py docstrings
- Updated singlevisit.rst to display make_poller_files.py documentation in the "Supporting Code" section

### CODE REVIEW

**Review by stsci-hack — CHANGES_REQUESTED** [review]
Nice framework for the new documentation and nice update to the API documentation.  

The file 'makecustommosaic.rst', though, should include answers to the following questions:
  - why would a user want to run this code? [science case, comparison to MVM products]
  - when the code is run, what kind of inputs (both images and parameters) are required and where would they come from?
  - when the code is run, what output products should be expected? Do they differ depending on the inputs?  
This information will allow users to understand this new tool better, not just how to run it, which will make it easier for people to know when they would need to use this code as opposed to the standard MVM products.

**Comment by dulude** [comment]
Hey @stsci-hack, the PR is ready for re-review.

**Review by stsci-hack — APPROVED** [review]
This will work well as the initial documentation for this task.

**Comment by dulude** [comment]
sorry. couple of minor cosmetic tweaks

**Review by stsci-hack — APPROVED** [review]

**Pull request merged**
