### PR TITLE
Enforce pixtopix verbose setting when not run as a script

### PR DESCRIPTION
**Pull request by mcara**
This PR fixes the behavior of `verbose` parameter to actually work as expected when `pixtopix` is not run as a script. In addition it also removes the `coords` parameter that has been deprecated for years. It is time to remove it.

### CODE REVIEW

**Comment by pllim** [comment]
You gotta ignore the bot for now until I have time to figure out how to take it over from @drdavella .

**Comment by mcara** [comment]
This PR fixes https://github.com/spacetelescope/drizzlepac/issues/395

**Comment by pllim** [comment]
Saying fixes after the fact won't autoclose the other issue. You gotta close #395 manually. FYI.

**Comment by mcara** [comment]
@pllim I know. I just wanted to have a record of this + link issue with PR.

**Pull request merged**
