### PR TITLE
Perform an experiment to determine if astroquery causes RT problems

### PR DESCRIPTION
**Pull request by mdlpstsci**
As an experiment to determine if astroquery is responsible for the regression test infrastructure failures, all tests which use astroquery_utils to acquire data (only the HAP tests use this capability) have had their tests set to SKIP at the module level.

### CODE REVIEW

**Comment by mdlpstsci** [comment]
Indeed, it is my plan to run the RTs "before" and "after" this update.  I am off to start the "before" now.

**Comment by nden** [comment]
Regression test run with this PR is here
https://plwishmaster.stsci.edu:8081/job/RT/job/drizzlepac/1688/

**Review by s-goldman — APPROVED** [review]

**Comment by mdlpstsci** [comment]
This PR has been superceded by PR#1606.  This PR can be closed.

**Comment by mdlpstsci** [comment]
This PR has been superceded by PR#1606.  This PR can be closed.

**Pull request closed without merging**
