### PR TITLE
HLA-1048: Redesign of readthedocs documentation

### PR DESCRIPTION
**Pull request by s-goldman**
I have redesigned the readthedocs documentation and the file organization of the docs. I folded all of the information into three categories: getting started, explanation, and API. I also created some new files, some of which with new information (e.g. citing_drizzlepac.rst), other that still need to be filled in (e.g. installation.rst). I have also resolved broken links throughout the package and documentation. Work still need to be done will be included in new Jira tickets.

### CODE REVIEW

**Comment by s-goldman** [comment]
Broken links were identified using the following

```
conda install -c conda-forge pytest-check-links
make html
pytest --check-links ./doc/build/html
```

**Comment by nden** [comment]
This needs a RTD build on PR enabled. @zacharyburnett may be able to help with that

**Comment by zacharyburnett** [comment]
> This needs a RTD build on PR enabled. @zacharyburnett may be able to help with that

It looks like I don't have admin access to the Drizzlepac RTD build, but for anyone who does, you should check the `Build pull requests for this project` setting on this page:
https://readthedocs.org/dashboard/drizzlepac/advanced/

**Comment by zacharyburnett** [comment]
the build had several warnings:
```
docstring of drizzlepac.ablot:7: WARNING: unknown document: 'LICENSE'
```

**Review by mdlpstsci — CHANGES_REQUESTED** [review]
First and foremost this is a difficult task (I know from experience), but you have done a very nice job of reorganizing and cleaning up the information!  **(1) I would say to the first order we just want the reorganized information to build.**  Were you able to get your branch to build the docs?  If yes, then the RTD pipeline gives the extra feedback to correct information so the docs build and can be viewed.  **(2) I suggest the discussion of the parameter files needs a "sub-landing" page.**  There are many files (nominal pipeline *.cfg, the HAP SVM JSONs, and the HAP MVM JSONs) which should be discussed at a high-level.  Once the parameter file landing page is done, then representative samples can be discussed.  You might want to pull the parameter file discussion out into a different ticket (both Jira and GitHub).

**Comment by zacharyburnett** [comment]
I'm not sure why this error occurs in `sphinx_rtd_theme`:
```
  File "/home/docs/checkouts/readthedocs.org/user_builds/drizzlepac/envs/1620/lib/python3.8/site-packages/sphinx_rtd_theme/layout.html", line 67, in top-level template code
    <link rel="stylesheet" href="{{ pathto('_static/' + style, 1) }}" type="text/css" />
jinja2.exceptions.UndefinedError: 'style' is undefined
```

**Comment by nden** [comment]
I don't know why the `sphinx_rtd_theme` error either. Most other software packages we maintain use the `stsci_rtd_theme`. It may be worth trying to replace it and see if it fixes the error.

https://github.com/spacetelescope/drizzlepac/blob/57a92bbb4430f64a3070325706a1413fcbbe74d1/doc/source/conf.py#L216

Also I'm not sure why a sphinx version is specified, it may be left from years ago. Try commenting it out.
https://github.com/spacetelescope/drizzlepac/blob/57a92bbb4430f64a3070325706a1413fcbbe74d1/doc/source/conf.py#L49

**Comment by nden** [comment]
Or perhaps this will help
https://github.com/spacetelescope/jwst/pull/7787

**Comment by s-goldman** [comment]
> Or perhaps this will help [spacetelescope/jwst#7787](https://github.com/spacetelescope/jwst/pull/7787)

Thanks, i'll try these possible fixes.

**Comment by nden** [comment]
The JWST fix seems to work.

**Comment by s-goldman** [comment]
Unfortunately, combinations of the above suggestions hasn't seemed to work. That being said, the docs can still be built locally. 

Using 'stsci_rtd_theme' results in an error locally of 'Theme not found', even after it is installed and imported.

**Comment by zacharyburnett** [comment]
> Unfortunately, combinations of the above suggestions hasn't seemed to work. That being said, the docs can still be built locally.
> 
> Using 'stsci_rtd_theme' results in an error locally of 'Theme not found', even after it is installed and imported.

I think this might be due to the fact that the `.rtd-environment.yaml` is never used; according to the `.readthedocs.yaml` and the RTD build log, it is still building a virtualenv, and using the deprecated `version` entry in the `python` block. To use `doc/.rtd-environment.yaml` you should use a config similar to this: https://github.com/spacetelescope/roman_datamodels/blob/26aeec807304e0feee70b0d7a14bd0b470624ead/.readthedocs.yaml#L23-L38

**Comment by zacharyburnett** [comment]
it looks like the docs build 🎉 

hosted at https://drizzlepac--1620.org.readthedocs.build/en/1620/

**Comment by s-goldman** [comment]
The code passes with the Mac build but not the linux. It's unclear if this is related to this PR.

**Comment by mdlpstsci** [comment]
@s-goldman The single test which is failing, test_svm_hrcsbc.py, is failing because the number of detected sources reported in the SBC total segmentation catalog fell below the lower tolerance.  For my own testing, I processed this dataset on my MacOS, on Linux, and downloaded data from MAST for comparison.  The number of sources in total catalogs is dependent not only the algorithms used, but also the source must be found in all of the associated filter catalogs.  If the source is not found in all of the filter catalogs, the row is removed from the total catalog. I have a PR in progress (#1631) which updates the number of "base" found sources for this particular catalog among other things.

I will note the version number of relevant packages is also different between MacOS and Linux.

**Comment by s-goldman** [comment]
> @s-goldman The single test which is failing, test_svm_hrcsbc.py, is failing because the number of detected sources reported in the SBC total segmentation catalog fell below the lower tolerance. For my own testing, I processed this dataset on my MacOS, on Linux, and downloaded data from MAST for comparison. The number of sources in total catalogs is dependent not only the algorithms used, but also the source must be found in all of the associated filter catalogs. If the source is not found in all of the filter catalogs, the row is removed from the total catalog. I have a PR in progress (#1631) which updates the number of "base" found sources for this particular catalog among other things.
> 
> I will note the version number of relevant packages is also different between MacOS and Linux.
> 
> No, your PR here is NOT at fault!

Thanks for this Michele. Other than this, the docs [successfully build](https://drizzlepac--1620.org.readthedocs.build/en/1620/). After I add the sub-landing page(s), I think it will be ready for a re-review. Thanks!

**Review by mdlpstsci — APPROVED** [review]
Thanks.  It turns out there is just a lot to describe, even at a high-level, with respect to the configuration parameters.

**Pull request merged**
